project_id = "nvpzjobotxvhpnedgvml"

[functions.analyze-financials]
verify_jwt = false

[functions.financial-chat]
verify_jwt = false

[functions.generate-presentation]
verify_jwt = false

[functions.classify-accounts]
verify_jwt = false

[functions.identify-file-type]
verify_jwt = false
